import { mkdtemp, mkdir, rm, symlink, writeFile, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { afterEach, describe, expect, it } from 'vitest'
import { codiconAsset, createEntry, gitAction, gitStatus, listFiles, pdfWorkerAsset, readDocument, renameEntry, saveDocument, uploadFile, workspaceImage, workspacePath, workspacePreviewFile } from '../src/host.ts'

const roots:string[]=[]
async function temp(){const value=await mkdtemp(join(tmpdir(),'dvw-'));roots.push(value);return value}
afterEach(async()=>{await Promise.all(roots.splice(0).map(path=>rm(path,{recursive:true,force:true})))})

describe('workspace filesystem',()=>{
  it('lists lazily and performs guarded mutations',async()=>{const root=await temp();await mkdir(join(root,'src'));await writeFile(join(root,'src','a.ts'),'one');expect((await listFiles(root,'')).map(x=>x.name)).toEqual(['src']);const doc=await readDocument(root,'src/a.ts');await saveDocument(root,'src/a.ts','two',doc.revision);expect(await readFile(join(root,'src','a.ts'),'utf8')).toBe('two');await createEntry(root,'src/b.ts','file');await renameEntry(root,'src/b.ts','src/c.ts');expect((await listFiles(root,'src')).map(x=>x.name)).toEqual(['a.ts','c.ts'])})
  it('rejects traversal and symlink escape',async()=>{const root=await temp();const outside=await temp();await writeFile(join(outside,'secret'),'x');await symlink(outside,join(root,'link'));await expect(workspacePath(root,'../x')).rejects.toMatchObject({code:'path-outside'});await expect(readDocument(root,'link/secret')).rejects.toMatchObject({code:'path-outside'})})
  it('hides external links and follows links that stay inside the workspace',async()=>{const root=await temp();const outside=await temp();await mkdir(join(root,'src'));await writeFile(join(root,'src','inside.txt'),'inside');await writeFile(join(outside,'outside.txt'),'outside');await symlink(join(root,'src'),join(root,'internal-link'),process.platform==='win32'?'junction':'dir');await symlink(outside,join(root,'external-link'),process.platform==='win32'?'junction':'dir');expect((await listFiles(root,'')).map(entry=>[entry.name,entry.kind])).toEqual([['internal-link','directory'],['src','directory']]);expect((await listFiles(root,'internal-link')).map(entry=>entry.name)).toEqual(['inside.txt']);expect((await readDocument(root,'internal-link/inside.txt')).content).toBe('inside')})
  it('rejects stale saves',async()=>{const root=await temp();await writeFile(join(root,'a'),'one');const doc=await readDocument(root,'a');await writeFile(join(root,'a'),'external');await expect(saveDocument(root,'a','mine',doc.revision)).rejects.toMatchObject({code:'revision-conflict'})})
  it('uploads files only to an existing workspace directory without overwriting',async()=>{const root=await temp();await mkdir(join(root,'uploads'));const entry=await uploadFile(root,'uploads','report.txt',Buffer.from('received'));expect(entry.path).toBe('uploads/report.txt');expect(await readFile(join(root,'uploads','report.txt'),'utf8')).toBe('received');await expect(uploadFile(root,'uploads','report.txt',Buffer.from('again'))).rejects.toMatchObject({code:'EEXIST'});await expect(uploadFile(root,'../outside','x.txt',Buffer.from('x'))).rejects.toMatchObject({code:'path-outside'});await expect(uploadFile(root,'uploads','../x.txt',Buffer.from('x'))).rejects.toMatchObject({code:'filename-invalid'})})
  it('serves only workspace images through the preview resolver',async()=>{const root=await temp();await writeFile(join(root,'preview.png'),'image');await writeFile(join(root,'notes.txt'),'text');expect(await workspaceImage(root,'preview.png')).toMatchObject({type:'image/png'});await expect(workspaceImage(root,'notes.txt')).rejects.toMatchObject({code:'unsupported-media'});await expect(workspaceImage(root,'../preview.png')).rejects.toMatchObject({code:'path-outside'})})
  it('serves PDF and Word documents through the protected preview resolver',async()=>{const root=await temp();await writeFile(join(root,'report.pdf'),'pdf');await writeFile(join(root,'report.docx'),'word');await writeFile(join(root,'notes.txt'),'text');expect(await workspacePreviewFile(root,'report.pdf')).toMatchObject({type:'application/pdf'});expect(await workspacePreviewFile(root,'report.docx')).toMatchObject({type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});await expect(workspacePreviewFile(root,'notes.txt')).rejects.toMatchObject({code:'unsupported-media'})})
})

describe('local Git',()=>{
  it('shows diffs for untracked and tracked files',async()=>{const root=await temp();const {execFile}=await import('node:child_process');const run=(args:string[])=>new Promise<void>((resolve,reject)=>execFile('git',args,{cwd:root},error=>error?reject(error):resolve()));await run(['init']);await run(['config','user.email','test@example.com']);await run(['config','user.name','Test']);await mkdir(join(root,'src'));await writeFile(join(root,'src','a.txt'),'first\n');let status=await gitStatus(root);expect(status.changes).toMatchObject([{path:'src/a.txt',untracked:true}]);const added=await gitAction(root,'diff','src/a.txt','untracked') as {diff:string};expect(added.diff).toContain('+first');await gitAction(root,'stage','src/a.txt');await gitAction(root,'commit',undefined,'initial');await writeFile(join(root,'src','a.txt'),'second\n');status=await gitStatus(root);expect(status.changes[0]?.path).toBe('src/a.txt');const changed=await gitAction(root,'diff','src/a.txt','worktree') as {diff:string};expect(changed.diff).toContain('-first');expect(changed.diff).toContain('+second')})
  it('returns graph commits and commit patches',async()=>{const root=await temp();const {execFile}=await import('node:child_process');const run=(args:string[])=>new Promise<void>((resolve,reject)=>execFile('git',args,{cwd:root},error=>error?reject(error):resolve()));await run(['init']);await run(['config','user.email','test@example.com']);await run(['config','user.name','Test']);await writeFile(join(root,'a.txt'),'first\n');await gitAction(root,'stage.all');await gitAction(root,'commit',undefined,'initial commit');const commits=await gitAction(root,'log') as Array<{hash:string;subject:string}>;expect(commits[0]?.subject).toBe('initial commit');const detail=await gitAction(root,'commit.show',undefined,commits[0]?.hash) as {diff:string};expect(detail.diff).toContain('initial commit');expect(detail.diff).toContain('+first')})
  it('lists every file in every returned commit and returns its patch',async()=>{const root=await temp();const {execFile}=await import('node:child_process');const run=(args:string[])=>new Promise<void>((resolve,reject)=>execFile('git',args,{cwd:root},error=>error?reject(error):resolve()));await run(['init']);await run(['config','user.email','test@example.com']);await run(['config','user.name','Test']);await writeFile(join(root,'a.txt'),'first\n');await gitAction(root,'stage.all');await gitAction(root,'commit',undefined,'initial');await writeFile(join(root,'a.txt'),'second\n');await writeFile(join(root,'b.txt'),'added\n');await gitAction(root,'stage.all');await gitAction(root,'commit',undefined,'second');const commits=await gitAction(root,'log') as Array<{hash:string}>;expect(commits.every(commit=>/^[0-9a-f]{40}$/i.test(commit.hash))).toBe(true);for(const commit of commits)expect((await gitAction(root,'commit.files',undefined,commit.hash) as unknown[]).length).toBeGreaterThan(0);const files=await gitAction(root,'commit.files',undefined,commits[0]?.hash) as Array<{path:string;status:string}>;expect(files).toEqual([{path:'a.txt',status:'M'},{path:'b.txt',status:'A'}]);const detail=await gitAction(root,'commit.file.diff','a.txt',commits[0]?.hash) as {diff:string};expect(detail.diff).toContain('-first');expect(detail.diff).toContain('+second')})
  it('discards tracked and untracked changes together',async()=>{const root=await temp();const {execFile}=await import('node:child_process');const run=(args:string[])=>new Promise<void>((resolve,reject)=>execFile('git',args,{cwd:root},error=>error?reject(error):resolve()));await run(['init']);await run(['config','user.email','test@example.com']);await run(['config','user.name','Test']);await run(['config','core.autocrlf','false']);await writeFile(join(root,'tracked.txt'),'original\n');await gitAction(root,'stage.all');await gitAction(root,'commit',undefined,'initial');await writeFile(join(root,'tracked.txt'),'changed\n');await writeFile(join(root,'untracked.txt'),'temporary\n');expect((await gitStatus(root)).changes).toHaveLength(2);await gitAction(root,'discard.all');expect((await gitStatus(root)).changes).toEqual([]);expect(await readFile(join(root,'tracked.txt'),'utf8')).toBe('original\n');await expect(readFile(join(root,'untracked.txt'),'utf8')).rejects.toMatchObject({code:'ENOENT'})})
})

describe('client assets',()=>{it('resolves the VS Code Codicon font',()=>{expect(codiconAsset()).toMatchObject({type:'font/ttf'});expect(codiconAsset().path).toMatch(/codicon\.ttf$/)});it('resolves the PDF.js module worker',()=>{expect(pdfWorkerAsset()).toMatchObject({type:'text/javascript; charset=utf-8'});expect(pdfWorkerAsset().path).toMatch(/pdf\.worker\.min\.mjs$/)})})
